on:
  push:
    paths:
      - '**.hs'
      - '**.nix'
      - 'nix/sources.json'
      - '**.cabal'
      - '.github/workflows/*'
    branches:
      - master
      - staging
  pull_request:
    paths:
      - '**.hs'
      - '**.nix'
      - 'nix/sources.json'
      - '**.cabal'
      - '.github/workflows/*'
jobs:
  check-formatting:
    name: Check source format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Cache Stack
        uses: actions/cache@v2.1.4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-formatting
          restore-keys: ${{ runner.os }}-stack-
      - name: Install fourmolu
        run: stack install fourmolu
      - name: Run fourmolu
        run: ./.github/format.sh
  lint:
    name: Check HLint hints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Set up HLint
        uses: haskell/actions/hlint-setup@v1
        with:
          version: 3.3.6
      - name: Lint
        run: ./.github/lint.sh
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        name: Set up nix and IOHK cache
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
      - uses: cachix/cachix-action@v10
        with:
          name: mlabs
          authToken: ${{ secrets.CACHIX_KEY }}
      - name: Cache cabal folder
        id: cabal
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal
      - name: Build the full ci derivation
        run: nix build .#check.x86_64-linux --extra-experimental-features nix-command --extra-experimental-features flakes
